import type { Metadata } from "next";
import localFont from "next/font/local";
import { Lato } from "next/font/google";
import "./globals.css";
import Loader from "./components/loader";
import Navbar from "./components/navbar";

const achiko = localFont({
  src: "./fonts/AchikoRegular.ttf",
  variable: "--font-achiko",
});

const lato = Lato({
  weight: [ "400", "700"],
  variable: "--font-lato",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${achiko.variable} ${lato.variable} antialiased`}
      >
        <Loader />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
