import type { Metadata } from "next";
import { Grand_Hotel, Lato } from "next/font/google";
import "./globals.css";
import Loader from "./components/loader";
import Navbar from "./components/navbar";

const grandHotel = Grand_Hotel({
  weight: "400",
  variable: "--font-grand-hotel",
  subsets: ["latin"],
});

const lato = Lato({
  weight: ["300", "400", "700"],
  variable: "--font-lato",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grandHotel.variable} ${lato.variable} antialiased`}
      >
        <Loader />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
